### ISSUE TITLE
React Native Notification Intergation

### ISSUE THREAD

**Issue by mkharibalaji** [kanzitelli/expo-rnn-starter#1]
Hi @kanzitelli ,
          Excellent Work.It would be great if we could have React Native Notification integrated with the current version of the template.

**Comment by kanzitelli** [comment]
Hello @mkharibalaji,

Thank you for the feedback! This is actually a good feature to have within the template. I am planning to use [React Native Notifications](https://github.com/wix/react-native-notifications) in the project I am working on now and once I successfully integrate it there and test it as well, I will add this library to the template. Sounds good? :)

**Comment by billel-boudchicha** [comment]
hi @kanzitelli 
Thank you for this starter. could you please tell me about the state of react-native-notifications , cuz i am planning to migrate from rn-firebase as it's become a payed library now.
thank you for your feedback

**Comment by kanzitelli** [comment]
Hello @billel-boudchicha!

Thank you for the feedback! I am going to be honest and say that I have not started integration yet because notifications are at the end of todo list of the app I am working on now but if it would be possible I will lift it up and do my best to do it as fast as I can.

And a few questions about notifications: Were you planning to use [notification library by Wix](https://github.com/wix/react-native-notifications)? And what are use cases in your app? I mean what initial configuration or set up would you like to see in the starter? 

Thank you. 

Kind regards and Happy New Year!

**Comment by juddey** [comment]
Subscribing to this thread. Planning to implement RN Notifications by Wix.

**Comment by kanzitelli** [comment]
Hey @juddey! Your help is very welcome and appreciated!

**Comment by juddey** [comment]
@kanzitelli update: have RN notifications "roughly" working on android now

**Comment by kanzitelli** [comment]
@juddey awesome news! I will start integrating RN notifications soon as one of my side project is getting done that was actually bootstrapped from this starter. Would you like to share your "roughly" working version?

**Comment by juddey** [comment]
Sure, give me a few days to give it a try and see what it will and wont do

**Comment by kanzitelli** [comment]
Hey guys! I have just integrated Expo modules to the starter. So it will be much easier to add notifications and other modules from Expo 🎉 
I am planning to create an `example` folder with some examples such as working and configured notifications, auth flow and other use cases. If anyone would be down to contribute, you are always welcome 🖖

**Comment by kanzitelli** [comment]
closed by #23 in release `v6.4.0`
