### ISSUE TITLE
Redux support

### ISSUE THREAD

**Issue by ussuritiger** [kanzitelli/expo-rnn-starter#19]
I've landed on this repo page from the showcases page of React Native Navigation. There it says that this starter kit supports both Redux and MobX. I've checked the commit history and found out that support for Redux was removed. Therefore I am wondering whether there was any problem you've encountered while using React Native Navigation with Redux or there are other reasons? Thanks.

**Comment by kanzitelli** [comment]
Hi @ussuritiger 

You are right, starting from v6.0.0 I have left only MobX implementation because I always use it and it became a bit hard to maintain both of them. However, I still believe that it was a good idea to have both implementations.

And no, there was no any problems integrating Redux to RNN. If you'd like to check Redux integration, you can follow to [v5.2.0](https://github.com/kanzitelli/expo-rnn-starter/tree/5.2.0) under `/srcRedux` folder.

**Comment by ussuritiger** [comment]
Thanks a lot @kanzitelli! Will check it out.
